### ISSUE TITLE
run "streamlit run app/app.py", there is a errror as the description.

### ISSUE THREAD

**Issue by lizhzh8** [liyucheng09/Selective_Context#13]
[2023-11-23 19:00:13,153] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-11-23 19:00:34.345 Uncaught app exception
Traceback (most recent call last):
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 264, in _get_or_create_cached_value
    cached_result = cache.read_result(value_key)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 312, in _handle_cache_miss
    cached_result = cache.read_result(value_key)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/caching/cache_resource_api.py", line 500, in read_result
    raise CacheKeyNotFoundError()
streamlit.runtime.caching.cache_errors.CacheKeyNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/wls/lzz/Selective_Context/app/app.py", line 270, in <module>
    model = load_model(lang)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 267, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 321, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/wls/lzz/Selective_Context/app/app.py", line 266, in load_model
    model = SelectiveContext(lang=lang)
  File "/wls/lzz/Selective_Context/app/app.py", line 45, in __init__
    self._prepare_phrase_tokenizer()
  File "/wls/lzz/Selective_Context/app/app.py", line 58, in _prepare_phrase_tokenizer
    self.nlp = spacy.load("en_core_web_sm", disable=["ner"])
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/__init__.py", line 51, in load
    return util.load_model(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/util.py", line 420, in load_model
    return load_model_from_package(name, **kwargs)  # type: ignore[arg-type]
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/util.py", line 453, in load_model_from_package
    return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)  # type: ignore[attr-defined]
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/en_core_web_sm/__init__.py", line 10, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/util.py", line 615, in load_model_from_init_py
    return load_model_from_path(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/util.py", line 488, in load_model_from_path
    nlp = load_model_from_config(config, vocab=vocab, disable=disable, exclude=exclude)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/util.py", line 525, in load_model_from_config
    nlp = lang_cls.from_config(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/language.py", line 1785, in from_config
    nlp.add_pipe(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/language.py", line 788, in add_pipe
    pipe_component = self.create_pipe(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/spacy/language.py", line 671, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/thinc/config.py", line 746, in resolve
    resolved, _ = cls._make(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/thinc/config.py", line 795, in _make
    filled, _, resolved = cls._fill(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/thinc/config.py", line 850, in _fill
    filled[key], validation[v_key], final[key] = cls._fill(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/thinc/config.py", line 849, in _fill
    promise_schema = cls.make_promise_schema(value, resolve=resolve)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/thinc/config.py", line 1057, in make_promise_schema
    return create_model("ArgModel", **sig_args)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/pydantic/main.py", line 990, in create_model
    return type(__model_name, (__base__,), namespace)
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/pydantic/main.py", line 299, in __new__
    fields[ann_name] = ModelField.infer(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/pydantic/fields.py", line 411, in infer
    return cls(
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/pydantic/fields.py", line 342, in __init__
    self.prepare()
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/pydantic/fields.py", line 451, in prepare
    self._type_analysis()
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/site-packages/pydantic/fields.py", line 550, in _type_analysis
    if issubclass(origin, Tuple):  # type: ignore
  File "/wls/anaconda3/envs/interpreter/lib/python3.10/typing.py", line 1134, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by liyucheng09** [comment]
cannot reproduce your error.
Mine works without problems.

here is my environment:
`pytorch-transformers          1.1.0
sentence-transformers         2.2.2
spacy-transformers            1.1.4
transformers                  4.28.1
spacy                         3.2.0
spacy-alignments              0.8.4
spacy-legacy                  3.0.12
spacy-loggers                 1.0.1
spacy-pkuseg                  0.0.28
spacy-transformers            1.1.4
en-core-web-sm                3.2.0
bs4                           0.0.1
evaluate                      0.4.0
openai                        0.27.2
pandas                        1.4.0
numpy                         1.22.1
pytorch-transformers          1.1.0
torch                         1.11.0
torchvision                   0.12.0
tqdm                          4.62.3
datasets                      2.11.0
ir-datasets                   0.5.4
filelock                      3.4.2`
